-- 建立 dorm_accordions 資料表
CREATE TABLE IF NOT EXISTS public.dorm_accordions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icon TEXT,
    title TEXT,
    content TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 建立 dorm_rooms 資料表
CREATE TABLE IF NOT EXISTS public.dorm_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    campus TEXT NOT NULL,
    gender TEXT NOT NULL,
    beds INTEGER NOT NULL,
    dorm TEXT NOT NULL,
    size TEXT,
    bed_size TEXT,
    bed_type TEXT,
    price TEXT,
    status TEXT,
    emoji TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 建立 dorm_facilities 資料表
CREATE TABLE IF NOT EXISTS public.dorm_facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icon TEXT,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 建立 dorm_contacts 資料表
CREATE TABLE IF NOT EXISTS public.dorm_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icon TEXT,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 清空資料，避免重複執行時資料重複
TRUNCATE TABLE public.dorm_accordions RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.dorm_rooms RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.dorm_facilities RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.dorm_contacts RESTART IDENTITY CASCADE;

-- 寫入 dorm_accordions 資料
INSERT INTO public.dorm_accordions (icon, title, content) VALUES
('fas fa-university', '明新大樓 — 一般樓層 (3-7樓)', '<p style="margin-top:14px;font-size:.88rem;color:#444;line-height:1.8">本區提供一般學生住宿，3 與 4 樓為女生樓層，5、6、7 樓為男生樓層。一層樓配置 28 間房間，每房 4 床，採光明亮、通風良好。</p>'),
('fas fa-globe', '明新大樓 — 國際生樓層 (8樓)', '<p style="margin-top:14px;font-size:.88rem;color:#444;line-height:1.8">8樓專為國際生規劃，共有 28 間房間，男女皆可申請入住混合層，提供多元文化交流的友善住宿環境。</p>'),
('fas fa-wheelchair', '身心障礙專屬房型', '<p style="margin-top:14px;font-size:.88rem;color:#444;line-height:1.8">本宿舍設有 4 間身心障礙專屬房（位於3樓女生樓層及6樓男生樓層各2間），每間2床。門口均配有<b>警示燈</b>，並設有無障礙衛浴及專屬安全設施。</p>'),
('fas fa-clipboard-list', '申請流程', '<ol style="padding-left:20px;line-height:2;color:#444;font-size:.92rem"><li>確認開放申請時間（依學務處公告）</li><li>登入校務系統完成線上申請</li><li>等候抽籤結果通知（Email / 校務系統）</li><li>繳交住宿費用（依規定期限）</li><li>辦理進住手續（攜帶學生證、繳費收據）</li></ol>'),
('fas fa-exclamation-triangle', '進住須知', '<ul style="padding-left:20px;line-height:2;color:#444;font-size:.92rem"><li>門禁時間：每日 23:00，逾時須向管理員登記</li><li>禁止攜帶電磁爐、瓦斯爐等明火設備</li><li>不得留宿非本舍舍生</li><li>公共區域請保持整潔</li><li>違規記點達標準者將取消住宿資格</li></ul>');

-- 寫入 dorm_rooms 資料
INSERT INTO public.dorm_rooms (name, campus, gender, beds, dorm, size, bed_size, bed_type, price, status, emoji, description) VALUES
('女生一般宿舍 (3~4樓)', '校本部', '女', 4, '學生宿舍', '約 8 坪', '長200cm×寬90cm', '上鋪床下書桌', '依公告為主', '可申請', '🌸', '一般女生宿舍房型，配置於3樓及4樓。一層樓有28間房間，環境舒適採光佳。'),
('男生一般宿舍 (5~7樓)', '校本部', '男', 4, '學生宿舍', '約 8 坪', '長200cm×寬90cm', '上鋪床下書桌', '依公告為主', '可申請', '🛏️', '一般男生宿舍房型，配置於5、6、7樓。一層樓有28間房間，環境舒適採光佳。'),
('國際生宿舍 (8樓)', '校本部', '男女皆可', 4, '學生宿舍', '約 8 坪', '長200cm×寬90cm', '上鋪床下書桌', '依公告為主', '可申請', '🌍', '專屬國際學生樓層，位於最高8樓，男女皆可申請入住混合層。全層共28間，提供多元文化交流的住宿空間。'),
('女生無障礙身障房 (3樓)', '校本部', '女', 2, '學生宿舍', '約 10 坪', '長200cm×寬105cm', '無障礙單人床', '依公告為主', '可申請', '♿', '專為身心障礙女同學設計。位於3樓，共2間。門口配有專屬安全警示燈，房內提供無障礙衛浴。'),
('男生無障礙身障房 (6樓)', '校本部', '男', 2, '學生宿舍', '約 10 坪', '長200cm×寬105cm', '無障礙單人床', '依公告為主', '可申請', '♿', '專為身心障礙男同學設計。位於6樓，共2間。門口配有專屬安全警示燈，房內提供無障礙衛浴。');

-- 寫入 dorm_facilities 資料
INSERT INTO public.dorm_facilities (icon, name, description) VALUES
('fas fa-wifi', '高速 Wi-Fi', '全棟覆蓋'),
('fas fa-tshirt', '洗衣烘乾', '投幣式設備'),
('fas fa-utensils', '簡易廚房', '備有微波爐'),
('fas fa-book', '自習閱讀室', '24小時開放'),
('fas fa-dumbbell', '健身房', '基本健身器材'),
('fas fa-tv', '交誼廳', '電視、沙發'),
('fas fa-shield-alt', '24h安全管理', '門禁刷卡'),
('fas fa-parking', '機車停車場', '持有停車證'),
('fas fa-broom', '清潔服務', '公區定期清掃'),
('fas fa-first-aid', '緊急救護', 'AED設備');

-- 寫入 dorm_contacts 資料
INSERT INTO public.dorm_contacts (icon, text) VALUES
('fas fa-map-marker-alt', '304 新竹縣新豐鄉新興路1號（行政大樓）'),
('fas fa-phone', '學生宿舍服務台：03-559-3142'),
('fas fa-envelope', 'dorm@must.edu.tw'),
('fas fa-clock', '週一至週五 08:00–17:00');
