-- 建立 dorm_accordions 資料表
CREATE TABLE IF NOT EXISTS public.dorm_accordions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icon TEXT,
    title TEXT,
    content TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 建立 dorm_rooms 資料表
CREATE TABLE IF NOT EXISTS public.dorm_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    campus TEXT NOT NULL,
    gender TEXT NOT NULL,
    beds INTEGER NOT NULL,
    dorm TEXT NOT NULL,
    size TEXT,
    bed_size TEXT,
    bed_type TEXT,
    price TEXT,
    status TEXT,
    emoji TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 建立 dorm_facilities 資料表
CREATE TABLE IF NOT EXISTS public.dorm_facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icon TEXT,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 建立 dorm_contacts 資料表
CREATE TABLE IF NOT EXISTS public.dorm_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icon TEXT,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 清空資料，避免重複執行時資料重複
TRUNCATE TABLE public.dorm_accordions RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.dorm_rooms RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.dorm_facilities RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.dorm_contacts RESTART IDENTITY CASCADE;

-- 寫入 dorm_accordions 資料
INSERT INTO public.dorm_accordions (icon, title, content) VALUES
('fas fa-university', '和平校區宿舍 — 學一舍', '<table class="info-table"><tr><th>舍別</th><th>地址</th><th>服務電話</th><th>校內分機</th></tr><tr><td>男一舍</td><td>106311 臺北市大安區師大路9號</td><td>02-77493316</td><td>3316</td></tr><tr><td>女一舍（含女一分舍）</td><td>106311 臺北市大安區師大路11號</td><td>02-77493316</td><td>3316</td></tr></table><p style="margin-top:14px;font-size:.88rem;color:#666">男一舍（含女一分舍）及女一舍均為6人冷氣寢室，學士班及研究生共用。</p>'),
('fas fa-building', '公館校區宿舍 — 學二舍・學七舍', '<table class="info-table"><tr><th>舍別</th><th>地址</th><th>服務電話</th><th>校內分機</th></tr><tr><td>學七舍（男女）</td><td rowspan="2">116059 臺北市文山區汀州路4段88號</td><td>02-77496928</td><td>6928</td></tr><tr><td>學二舍（男二舍・女二舍）</td><td>02-77496920</td><td>6920</td></tr></table>'),
('fas fa-clipboard-list', '申請流程', '<ol style="padding-left:20px;line-height:2;color:#444;font-size:.92rem"><li>確認開放申請時間（依學務處公告）</li><li>登入校務系統完成線上申請</li><li>等候抽籤結果通知（Email / 校務系統）</li><li>繳交住宿費用（依規定期限）</li><li>辦理進住手續（攜帶學生證、繳費收據）</li></ol>'),
('fas fa-exclamation-triangle', '進住須知', '<ul style="padding-left:20px;line-height:2;color:#444;font-size:.92rem"><li>門禁時間：每日 23:00，逾時須向管理員登記</li><li>禁止攜帶電磁爐、瓦斯爐等明火設備</li><li>不得留宿非本舍舍生</li><li>公共區域請保持整潔</li><li>違規記點達標準者將取消住宿資格</li></ul>'),
('fas fa-dollar-sign', '收費標準', '<table class="info-table"><tr><th>校區</th><th>舍別</th><th>床數</th><th>每學期費用</th></tr><tr><td rowspan="3">和平校區</td><td>男一舍</td><td>6床</td><td>約 NT$13,000</td></tr><tr><td>女一分舍 4人房</td><td>4床</td><td>約 NT$15,000</td></tr><tr><td>女一舍</td><td>6床</td><td>約 NT$13,000</td></tr><tr><td rowspan="5">公館校區</td><td>學七舍</td><td>4床</td><td>約 NT$18,000</td></tr><tr><td>女二舍 2人房</td><td>2床</td><td>約 NT$22,000</td></tr><tr><td>女二舍 4人房</td><td>4床</td><td>約 NT$18,000</td></tr><tr><td>男二舍 2人房</td><td>2床</td><td>約 NT$22,000</td></tr><tr><td>男二舍 4人房</td><td>4床</td><td>約 NT$18,000</td></tr></table><p style="margin-top:12px;font-size:.82rem;color:#888">※ 費用依每學年公告為準，以上為參考金額。</p>');

-- 寫入 dorm_rooms 資料
INSERT INTO public.dorm_rooms (name, campus, gender, beds, dorm, size, bed_size, bed_type, price, status, emoji, description) VALUES
('男一舍 — 6人冷氣寢室', '和平校區', '男', 6, '學一舍', '19.8坪 (6.0坪/室)', '長192cm×寬90cm', '上鋪床下書桌（特殊寢室除外）', 'NT$13,000/學期', '可申請', '🛏️', '和平校區男生宿舍，6人一室，配備冷氣、上下舖及個人書桌，安全管理24小時。'),
('女一分舍 — 4人冷氣寢室', '和平校區', '女', 4, '學一舍', '19.8坪 (6.0坪/室)', '長192cm×寬90cm', '上鋪床下書桌（特殊寢室除外）', 'NT$15,000/學期', '可申請', '🌸', '和平校區女生分舍，4人一室，空間較寬敞，環境溫馨舒適。'),
('女一舍 — 6人冷氣寢室', '和平校區', '女', 6, '學一舍', '19.8坪 (6.0坪/室)', '長192cm×寬90cm', '上鋪床下書桌（特殊寢室除外）', 'NT$13,000/學期', '額滿', '🌺', '和平校區女生宿舍，6人一室，設有交誼廳、自習室與洗衣間。'),
('學七舍 — 4人冷氣寢室', '公館校區', '男', 4, '學七舍', '30.0坪 (9.1坪/室)', '長230cm×寬90cm', '上鋪床下書桌（特殊寢室除外）', 'NT$18,000/學期', '可申請', '🏠', '公館校區男女合院，4人一室，房間面積較大，生活機能完善。'),
('女二舍 — 2人冷氣寢室', '公館校區', '女', 2, '學二舍', '23.9坪 (7.2坪/室)', '長215cm×寬105cm', '下舖床', 'NT$22,000/學期', '可申請', '💐', '公館校區女生宿舍，2人一室，私密性高，配備下舖寬床，寢室舒適。'),
('女二舍 — 4人冷氣寢室', '公館校區', '女', 4, '學二舍', '23.9坪 (7.2坪/室)', '長205cm×寬105cm', '上鋪床下書桌（特殊寢室除外）', 'NT$18,000/學期', '額滿', '🌷', '公館校區女生4人房，合理費用享有獨立衛浴，生活便利。'),
('男二舍 — 2人冷氣寢室', '公館校區', '男', 2, '學二舍', '23.9坪 (7.2坪/室)', '長215cm×寬105cm', '下舖床', 'NT$22,000/學期', '可申請', '🏡', '公館校區男生2人房，房間空間充裕，適合注重隱私的同學。'),
('男二舍 — 3人冷氣寢室', '公館校區', '男', 3, '學二舍', '23.9坪 (7.2坪/室)', '長220cm×寬105cm', '下舖床', 'NT$20,000/學期', '可申請', '🏘️', '公館校區男生3人房，提供3張下舖寬床，每位同學各有獨立書桌空間。'),
('男二舍 — 4人冷氣寢室', '公館校區', '男', 4, '學二舍', '23.9坪 (7.2坪/室)', '長205cm×寬105cm', '上鋪床下書桌（特殊寢室除外）', 'NT$18,000/學期', '可申請', '🏢', '公館校區男生4人房，費用實惠，鄰近公共設施，交通便利。');

-- 寫入 dorm_facilities 資料
INSERT INTO public.dorm_facilities (icon, name, description) VALUES
('fas fa-wifi', '高速 Wi-Fi', '全棟覆蓋'),
('fas fa-tshirt', '洗衣烘乾', '投幣式設備'),
('fas fa-utensils', '簡易廚房', '備有微波爐'),
('fas fa-book', '自習閱讀室', '24小時開放'),
('fas fa-dumbbell', '健身房', '基本健身器材'),
('fas fa-tv', '交誼廳', '電視、沙發'),
('fas fa-shield-alt', '24h安全管理', '門禁刷卡'),
('fas fa-parking', '機車停車場', '持有停車證'),
('fas fa-broom', '清潔服務', '公區定期清掃'),
('fas fa-first-aid', '緊急救護', 'AED設備');

-- 寫入 dorm_contacts 資料
INSERT INTO public.dorm_contacts (icon, text) VALUES
('fas fa-map-marker-alt', '304 新竹縣新豐鄉新興路1號（行政大樓）'),
('fas fa-phone', '學生宿舍服務台：03-559-3142'),
('fas fa-envelope', 'dorm@must.edu.tw'),
('fas fa-clock', '週一至週五 08:00–17:00');
